version: "3"

services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py create_default_superuser &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  bot:
    build:
      context: .
    volumes:
      - ./:/app
    command: python3 social_media_api_bot/bot.py

    depends_on:
      - app

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - .env
