# Generated by Django 4.2.6 on 2023-10-13 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0002_alter_user_last_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_request",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 13, 18, 1, 58, 514942)
            ),
        ),
    ]
