# Generated by Django 4.2.6 on 2023-10-13 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_request",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 13, 17, 32, 15, 108149)
            ),
        ),
    ]
